version: '3'
services:
  deploy:
    image: dapp-deploy
    build:
      context: .
      dockerfile: Dockerfile.dapp
    env_file:
      - .env
    deploy:
      replicas: 0
    volumes:
      - ./deployments:/dapp/deployments
    dns:
      - 8.8.8.8
      - 8.8.4.4

  backend:
    image: dapp-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - 3000:3000
    dns:
      - 8.8.8.8
      - 8.8.4.4